### ISSUE TITLE
Issue with Python v3.10

### ISSUE THREAD

**Issue by Taomyn** [thinkst/opencanary#163]
I just upgraded my OpenCanary machine from Fedora Server 34 to 35 and along with it comes Python 3.10 which unfortunately broke OpenCanary. I did a fresh install of OpenCanary using PIP to be sure I have the latest version. The error is:

```
  File "/root/env/lib/python3.10/site-packages/jinja2/tests.py", line 13, in <module>
    from collections import Mapping
builtins.ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib64/python3.10/collections/__init__.py)

```
Making a modification to tests.py to use collections.abc fixes the problem. After that everything seems to be running fine.

**Comment by HybridAU** [comment]
Hey @Taomyn thanks for this bug report, it looks like this is because we were using an old version of Jinja2 that doesn't work with Python 3.10, @joewesch has just done a PR that [updates](https://github.com/thinkst/opencanary/pull/175/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R16) Jinja2 so it should support Python 3.10 soon.

**Comment by jeffshead** [comment]
I get the same error after a fresh install. I tried both PIP and Git installations. As you can see from below, I have v3.0.0-1:

`$ sudo apt-get install python3-jinja2
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-jinja2 is already the newest version (3.0.3-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`

I've just about given up. I have tried to install OpenCanary on a Raspberry Pi 4 at least a dozen times and in a Ubuntu Server VM five times. I always get errors. None of the tutorials found on the Internet, including the instruction found here, work.

**Comment by jayjb** [comment]
Hi @jeffshead,

Sorry about the hassle getting it installed. I would've pointed you at installing via the github repo instead of the pypi package since the github repo was slightly further ahead. Would you mind trying to install the new version?

Im sorry its been such a hassle. Its supposed to be easy and fun, but clearly we failed you there.

**Comment by jayjb** [comment]
Closing issue due to lack of activity. Please re-open if you still have the same issue.
